use_gpu: true

data:
    sr: 16000
    shift_ms: 10
    fftl: 1024
    num_mels: 80
    hop_length: 160
    top_db: 120

directories:
    root: /home/john/Datasets/VCTK-Corpus/wav48/
    text: /home/john/Datasets/VCTK-Corpus/txt/
    all_audio: audio/
    speakers: speakers/
    silence_removed: silence_removed/
    features: features/
    exps: exps/
    hashed_embeddings: hashed/

model:
    batch_first: true
    lr: 0.001
    binary_embedding_length: 16

train:
    log_step: 50
    model_save_step: 20000
    num_epochs: 50000
    batch_size: 8
    class_history: 50
    regular_epochs: 10000

hash:
    train_val_split: 0.98
    s: 30

vctk:
    num_speakers: 109








