use_gpu: true

data:
    sr: 16000
    shift_ms: 10
    fftl: 1024
    num_mels: 80
    hop_length: 160
    top_db: 120

directories:
    root: /home/john/Datasets/VCTK-Corpus-0.92/wav48_silence_trimmed/
    text: /home/john/Datasets/VCTK-Corpus-0.92/txt/
    speaker_info: /home/john/Datasets/VCTK-Corpus-0.92/speaker-info.txt
    silence_removed: silence_removed/
    all_audio: audio/
    speakers: speakers/
    features: features/
    exps: exps/
    hashed_embeddings: hashed/
    continuous_embeddings: cont_embed/

model:
    batch_first: true
    lr: 0.001
    binary_embedding_length: 128

train:
    log_step: 10
    model_save_step: 2000
    num_epochs: 50000
    batch_size: 16

hash:
    train_val_split: 0.98
    s: 30

vctk:
    num_speakers: 110








